# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          delmaSong
baseurl:        ""
url:            "https://www.delmaSong.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         delmaSong
  url:          https://delmaSong.github.io/
  email:        sdy2856@gmail.com
  github:       delmaSong

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/delmaSong/delmaSong.github.io
